# Generated by Django 4.0.4 on 2022-05-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=30)),
                ('dset2', models.CharField(default='Beaudoin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ASM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insect', models.CharField(default='Jack Pine Budworm', max_length=50)),
                ('dtype', models.CharField(default='Mortality', max_length=50)),
                ('year', models.IntegerField(default=2018)),
            ],
        ),
        migrations.CreateModel(
            name='SPEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField()),
                ('dset', models.CharField(default='Beaudoin', max_length=50)),
                ('hspecies', models.CharField(default='Jack Pine', max_length=50)),
            ],
        ),
    ]
