# Generated by Django 4.0.4 on 2022-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FILTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year1', models.IntegerField(default=2009)),
                ('year2', models.IntegerField(default=2021)),
            ],
        ),
    ]
