# Generated by Django 4.0.4 on 2022-05-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0002_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.CharField(default='PlaceHolder', max_length=5000)),
            ],
        ),
    ]
