# Generated by Django 4.0.4 on 2022-05-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0003_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='area',
            field=models.IntegerField(default=0.0036),
        ),
    ]
