# Generated by Django 4.0.4 on 2022-05-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0004_filter_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='area',
            field=models.FloatField(default=0.0324),
        ),
    ]
