# Generated by Django 4.0.4 on 2022-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0005_alter_filter_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEOM2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry2', models.CharField(default='PlaceHolder', max_length=50000)),
            ],
        ),
        migrations.AlterField(
            model_name='geom',
            name='geometry',
            field=models.CharField(default='PlaceHolder', max_length=50000),
        ),
    ]
