# Generated by Django 4.0.4 on 2022-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0006_geom2_alter_geom_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASM_Geom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_geom', models.CharField(default='PlaceHolder', max_length=50000)),
            ],
        ),
    ]
