# Generated by Django 4.0.4 on 2022-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0008_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='etype',
        ),
        migrations.AddField(
            model_name='export',
            name='nsite',
            field=models.IntegerField(default=5),
        ),
    ]
