# Generated by Django 4.0.4 on 2022-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0009_remove_export_etype_export_nsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FORCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='No', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='droad',
            field=models.FloatField(default=1),
        ),
    ]
