# Generated by Django 4.0.4 on 2022-06-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0011_alter_asm_insect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='dset2',
            field=models.CharField(choices=[('Beaudoin', 'Beaudoin')], default='Beaudoin', max_length=50),
        ),
        migrations.AlterField(
            model_name='asm',
            name='dtype',
            field=models.CharField(choices=[('Light', 'Light'), ('Moderate-Severe', 'Moderate-Severe'), ('Mortality', 'Mortality')], default='Mortality', max_length=50),
        ),
        migrations.AlterField(
            model_name='asm_geom',
            name='asm_geom',
            field=models.CharField(default='PlaceHolder', max_length=5000000),
        ),
        migrations.AlterField(
            model_name='geom',
            name='geometry',
            field=models.CharField(default='PlaceHolder', max_length=5000000),
        ),
        migrations.AlterField(
            model_name='geom2',
            name='geometry2',
            field=models.CharField(default='PlaceHolder', max_length=5000000),
        ),
        migrations.AlterField(
            model_name='spec',
            name='dset',
            field=models.CharField(choices=[('Beaudoin', 'Beaudoin')], default='Beaudoin', max_length=50),
        ),
        migrations.AlterField(
            model_name='spec',
            name='hspecies',
            field=models.CharField(choices=[('Jack Pine', 'Jack Pine'), ('Balsam Fir', 'Balsam Fir'), ('White Spruce', 'White Spruce'), ('Black Spruce', 'Black Spruce'), ('All SBW Host Species', 'All SBW Host Species')], default='Jack Pine', max_length=50),
        ),
    ]
