# Generated by Django 4.0.6 on 2022-07-27 19:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0012_alter_age_dset2_alter_asm_dtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGEOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageom', models.CharField(default='PlaceHolder', max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='PAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Step Title')),
            ],
        ),
        migrations.AlterField(
            model_name='export',
            name='nsite',
            field=models.IntegerField(default=0),
        ),
    ]
