# Generated by Django 4.0.6 on 2022-07-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0013_ageom_page_alter_export_nsite_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Default description')),
                ('types', models.CharField(choices=[('DDN', 'Dropdown'), ('SLD', 'Slider')], default='DDN', max_length=3)),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('step', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sitemap.page')),
            ],
        ),
        migrations.CreateModel(
            name='CHOICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sitemap.option')),
            ],
        ),
    ]
