# Generated by Django 4.0.6 on 2022-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0014_option_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='maximum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='minimum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='step',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
