# Generated by Django 4.0.6 on 2022-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0016_option_attribute_option_geofile_page_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='operation',
            new_name='betweenStepOperation',
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='operationType',
            field=models.TextField(null=True),
        ),
    ]
