# Generated by Django 4.0.6 on 2022-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0018_option_possiblevalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='possibleValues',
        ),
        migrations.AddField(
            model_name='choice',
            name='possibleValues',
            field=models.TextField(null=True),
        ),
    ]
