# Generated by Django 4.0.6 on 2022-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0019_remove_option_possiblevalues_choice_possiblevalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='possibleValues',
        ),
    ]
