# Generated by Django 4.0.6 on 2022-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0020_remove_choice_possiblevalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='uuid',
            field=models.CharField(default='PlaceHolder', max_length=100),
        ),
    ]
