# Generated by Django 4.0.6 on 2022-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0021_geom_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geom',
            name='uuid',
            field=models.CharField(default='PlaceHolder', max_length=100, unique=True),
        ),
    ]
