# Generated by Django 4.0.6 on 2022-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0022_alter_geom_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='geom',
            name='cachedGeometry',
            field=models.CharField(default='PlaceHolder', max_length=5000000),
        ),
    ]
