# Generated by Django 4.0.6 on 2022-08-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0023_geom_cachedgeometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='operation',
            field=models.CharField(choices=[('EQU', 'Equal'), ('GOE', 'GreaterOrEqual'), ('SOE', 'SmallerOrEqual'), ('STG', 'StrictlyGreater'), ('STS', 'StrictlySmaller')], default='EQU', max_length=3),
        ),
    ]
